baseURL = 'https://emmyperez.net/'
languageCode = 'en-us'
title = 'Emmy Perez'

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
github = 'emmyp'   # github.com/emmyp
linkedin = 'emmyperez' # linkedin.com/in/emmyperez

# home page profile
avatar = 'emmy.perez1@gmail.com'                  # gravatar email or image url
name = 'Emmy Perez'
bio = 'Data Scientist'


# misc
disableHLJS = true                      # disable highlight.js
disablePostNavigation = true            # disable post navigation
monoDarkIcon = true                     # show monochrome dark mode icon
favicon = "favicon.ico"                 # customize the default favicon
appleTouchIcon = "apple-touch-icon.png" # customize the default Apple touch icon
direction = "ltr"                       # RTL support for Right-to-left languages
